baseURL = "https://iva-tutor.ru/"
languageCode = "en-Us"
paginate = 6
theme = "portio"
title = "Психолог и тьютор для вашего ребенка"
# Main Menu
[[menu.main]]
name = "Обо мне"
url = "#home"
weight = 1
[[menu.main]]
name = "Тьюторство"
url = "#about"
weight = 2
[[menu.main]]
name = "Направления работ"
url = "#service"
weight = 3
[[menu.main]]
name = "Мой опыт"
url = "#resume"
weight = 5

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Пишите в мессенджеры и читайте мой телеграм-канал:"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/myyvzerl"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"


# Social icons
[[params.social]]
icon = "fa-brands fa-whatsapp"
url = "https://wa.clck.bar/79774596820"
weight = 1
[[params.social]]
icon = "fa-brands fa-telegram"
url = "https://t.me/iva_tutor/"
weight = 2
[[params.social]]
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/iva_psych/"
weight = 3
